### ISSUE TITLE
Cannot upload to online Arduino editor

### ISSUE THREAD

**Issue by alexruffell** [DFRobot/DFRobot_MCP23017#1]
In order to upload this library to the online arduino editor, there must be a file called library.properties in the root folder.

https://github.com/neu-rah/Arduino-VirtualPins/wiki/Arduino-IDE-1.5:-Library-specification

I am trying to create this file, but it would be great if it could be part of the distribution to make it easier for everyone.

**Comment by Arya11111** [comment]
Thanks for the suggestion, it has been added, you can download it via Arduino IDE
